# Generated by Django 5.1.3 on 2024-11-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=20)),
                ('_author', models.CharField(max_length=25)),
                ('_published_date', models.DateField()),
                ('_format', models.CharField(max_length=10)),
                ('_size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LibroFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=20)),
                ('_author', models.CharField(max_length=25)),
                ('_published_date', models.DateField()),
                ('_pages_amount', models.IntegerField()),
            ],
        ),
    ]
